[package]
name = "rros"
version = "0.1.1"
authors = ["ewoudje <ewoud.dierickx@hotmail.be>"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.bootimage]
default-target = "x86_64-rros.json"

[dependencies]
bootloader = "0.3.4"
